#! /usr/bin/env sh

LEGEND_HOME="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

case "$1" in
start)
  ${LEGEND_HOME}/legend-engine.sh start
  ${LEGEND_HOME}/legend-sdlc.sh start
  ${LEGEND_HOME}/legend-studio.sh start
  ;;
stop)
   ${LEGEND_HOME}/legend-engine.sh stop
   ${LEGEND_HOME}/legend-sdlc.sh stop
   ${LEGEND_HOME}/legend-studio.sh stop
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   ${LEGEND_HOME}/legend-engine.sh status
   ${LEGEND_HOME}/legend-sdlc.sh status
   ${LEGEND_HOME}/legend-studio.sh status
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
